# Generated by Django 3.2.6 on 2022-02-13 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

data = {}


def clean_data(apps, schema):
    Article = apps.get_model('blog', 'Article')
    Category = apps.get_model('blog', 'Category')
    for article in Article.objects.all():
        data[article.id] = {'author': article.author,
                            'category': article.category}
        article.author = ""
        Category.objects.get_or_create(title=article.category)
        article.category = ""
        article.save()


def fix_data(apps, schema):
    Category = apps.get_model('blog', 'Category')
    Article = apps.get_model('blog', 'Article')
    User = apps.get_model('account', 'User')
    for article in Article.objects.all():
        article.author = User.objects.get(
            username=data[article.id]['author'])
        article.category = Category.objects.get(
            title=data[article.id]['category'])
        article.updated = article.created
        article.published = article.created
        article.status = 'p'
        article.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.RunPython(
            code=clean_data,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(
                choices=[('p', 'publish'), ('d', 'draft')], default='d', max_length=1),
        ),
        migrations.AddField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category'),
        ),
        migrations.RunPython(
            code=fix_data,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
